name: Release process

on:
  release:
    types: [ published ]

jobs:
  deb12:
    name: Debian 12 release package building
    runs-on: ubuntu-latest
    container: ghcr.io/yeti-switch/yeti-web/build-image:bookworm
    services:
      db:
        image: ghcr.io/yeti-switch/yeti-web/pgsql:16

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set git safe directory
        run: git config --global --add safe.directory '*'

      - name: Build package
        run: make package
        env:
          YETI_DB_HOST: db
          YETI_DB_PORT: 5432
          CDR_DB_HOST: db
          CDR_DB_PORT: 5432
          SECRET_KEY_BASE: SFIVgccCTnlVm8Z244b07T0EGu8QM7BsLe1UMmXYBEZGYTUwYJzXdhwtvEL1nmui

      - name: Save deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb12-package
          path: /__w/yeti-web/*.deb

      - name: Calculate version from ${{github.ref}}
        env:
          PKG_TAG: ${{github.ref}}
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${PKG_TAG#refs/tags/})"
        id: extract_tag

      - name: calculate repo branch
        env:
          PKG_TAG: ${{github.ref}}
        shell: bash
        run: echo "##[set-output name=tag;]$(v=${PKG_TAG##*/};major_version=${v%\.[0-9]*};echo $major_version)"
        id: extract_branch

      - uses: yeti-switch/upload-debian-pkg-action@v2
        with:
          pkgs: '../*.deb'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          s3_prefix: ${{steps.extract_branch.outputs.tag}}
          s3_access_key_id: ${{ secrets.DEB_AWS_ACCESS_KEY_ID }}
          s3_secret_access_key: ${{ secrets.DEB_AWS_SECRET_ACCESS_KEY }}
          s3_endpoint_url: ${{ secrets.DEB_AWS_ENDPOINT }}        

  deb12_container:
    name: Debian 12 release container
    needs: deb12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: deb12-package

      - name: Display structure of downloaded files
        run: ls -la

      - name: Display path
        run: pwd

      - name: Calculate version from ${{github.ref}}
        env:
          PKG_TAG: ${{github.ref}}
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${PKG_TAG#refs/tags/})"
        id: extract_tag

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/stable-package.Dockerfile
          push: true
          tags: ghcr.io/yeti-switch/yeti-web:${{steps.extract_tag.outputs.tag}}
